name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: taskmanager
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Backend Dependencies
      run: |
        cd server
        npm install

    - name: Run Backend Tests
      run: |
        cd server
        npm test

    - name: Install Frontend Dependencies
      run: npm install

    - name: Run Frontend Tests
      run: npm test

    - name: Build Frontend
      run: npm run build

    - name: Build Backend
      run: |
        cd server
        npm run build
